### PR TITLE
Add StatusBar Icon Style Settings.

### PR DESCRIPTION
**Pull request by lx200916**
Fix Issue #18 .

Add New StatusBar Icon Styles.

image

### CODE REVIEW

**Comment by spencerwooo** [comment]
Hi, sorry for the late review.

I would prefer a dropdown for the selection. Something like:

<table>
<tr>
<th></th>
<th></th>
</tr>
</table>

**Comment by lx200916** [comment]
> Hi, sorry for the late review.
> 
> I would prefer a dropdown for the selection. Something like:
> 
> 	

U mean like this?
image
image

**Comment by spencerwooo** [comment]
Ahh, ok then. I'll figure something out for this design a bit later. And thanks for the PR ;)

**Comment by lx200916** [comment]
Cool😁

**Comment by spencerwooo** [comment]
Supersede by [v1.12.126](https://github.com/spencerwooo/PaimonMenuBar/releases/tag/v1.12.126)

**Pull request closed without merging**
